spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/travel_agency}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:TU_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY:TU_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:TU_API_SECRET}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
